### ISSUE TITLE
question 74

### ISSUE THREAD

**Issue by komalvhanmane** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#160]
You are given two arrays of strings that represent two inclusive events that happened on the same day, event1 and event2, where:

event1 = [startTime1, endTime1] and
event2 = [startTime2, endTime2].
Event times are valid 24 hours format in the form of HH:MM.

A conflict happens when two events have some non-empty intersection (i.e., some moment is common to both events).

Return true if there is a conflict between two events. Otherwise, return false.

 

Example 1:

Input: event1 = ["01:15","02:00"], event2 = ["02:00","03:00"]
Output: true
Explanation: The two events intersect at time 2:00.

**Comment by ArtiHere** [comment]
Name : Arti Tambade
Branch : IT
College : MKSSS's CCOEW
Please assign this issue to me

**Comment by ShrutikaK2911** [comment]
Name : Shrutika Kaperavenollu
CCOEW
Branch : IT
I would like to work on this issue.
Can you please assign me this issue

**Comment by ManasiGDeshmukh** [comment]
Name : Manasi Deshmukh
CCOEW
Branch : Computer Engineering
I would like to work on this issue.
Can you please assign me this issue ?

**Comment by sayli2003** [comment]
Sayli Borole
CCOEW
Computer
I would like to work on this issue.

**Comment by pranotip283** [comment]
Pranoti Patil
CCOEW
Comp
Can you assign me this issue?

**Comment by ruchagaikwad567** [comment]
Rucha Gaikwad 
PCCOER
Computer
Can you assign me this issue ?
