### ISSUE TITLE
Design a vote counting machine

### ISSUE THREAD

**Issue by RuchikaSuryawanshi7** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#169]
Design a vote counting machine that can input valid candidates' names and vote cast list, we need your help to write a function to find the number of votes cast against each good candidate, invalid vote counts, and finally the winner's name.

**Note:** If two candidates have the same votes then the winner can be finalized based on the order of valid candidates. If the number of invalid ballots is more or if the vote casted list is empty then output Winner = N/A

Input:
Valid Candidates Name: ["A", "B","C"]
Vote Casted: ["A","F","A", "B", "A", "B", "A", "C","E"]

output:
A=4 B=2 C=1 invalidVotes=2 Winner = A

Test Case: Sample Input For Custom Testing:
3
A
B
C
9
A
F
A
B
A
B
A
C
E

Sample Output:
A=4 B=2 C=1 invalidVotes=2 Winner A

_**while submitting your solution, add the question heading as a comment in your solution file**_

**Comment by AnnadaD** [comment]
Annada Dash
CCOEW
Computer Engineering
I would like to work on this issue
Can you please assign me this issue

**Comment by NikitaMiraje** [comment]
Nikita Miraje
CCOEW
E&TC
I would like to work on this issue
Can you please assign me this issue???

**Comment by ManasiGDeshmukh** [comment]
hey
I'm Manasi Deshmukh
CCOEW
Computer Engineering

I want to work on this issue
Can you assign this to me?

**Comment by gaurijoshi22** [comment]
Gauri Joshi
Cummins College of Engineering for Women, Pune
Dept- SY-IT
I would like to work on this issue.
Please assign me this issue.

**Comment by RuchikaSuryawanshi7** [comment]
I'm assigning this issue to all, whoever completes's first will get merged there PR

**Comment by ManasiGDeshmukh** [comment]
@RuchikaSuryawanshi7  Created a pull request
