### ISSUE TITLE
Improve the Readme file of the Repository 

### ISSUE THREAD

**Issue by RuchikaSuryawanshi7** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#170]

**Comment by ManasiGDeshmukh** [comment]
hey
I'm Manasi Deshmukh
CCOEW
Computer Engineering

I want to work on this issue
Can you assign this to me?

**Comment by gaurijoshi22** [comment]
Gauri Joshi
Cummins College of Engineering for Women, Pune
Dept- SY-IT
I would like to work on this issue.
Please assign me this issue.

**Comment by ManasiGDeshmukh** [comment]
@RuchikaSuryawanshi7 Created a pull request...
