### ISSUE TITLE
Create an Array.md explaining Array data-structure 

### ISSUE THREAD

**Issue by RuchikaSuryawanshi7** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#172]
- Explain the Array data structure
- how it works
- how to create
- try to add code snippets, pictures & gif's  explaining the concept
- Time complexity, the Space complexity of each operation performed on an array
**Note: add your readme.MD in Data structure/ Array/ your file**

**Comment by gaurijoshi22** [comment]
Gauri Joshi
Cummins College of Engineering for Women, Pune
Dept- SY-IT
I would like to work on this issue.
Please assign me this issue.

**Comment by Kriti-2308** [comment]
Kritika Dubey
Cummins college of engineering
Sy-IT
I would like to work on this issue
