### ISSUE TITLE
Create an Queue.md explaining Queue data-structure

### ISSUE THREAD

**Issue by RuchikaSuryawanshi7** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#180]
- Explain the Queue Data structure
- how it works
- how to create
- try to add code snippets, pictures & gif's explaining the concept
- Time complexity, the Space complexity of each operation performed on the Queue
- Explain functions used in Queue

Note: add your readme.MD in Data structure/Queue/ your file

**Comment by siddhesh-coder** [comment]
Hi can you plz assign me this issue

**Comment by Kriti-2308** [comment]
Kritika Dubey
Cummins college of engineering
SY-IT
I would like to work on this issue please assign it to me

**Comment by sejal-phatangare** [comment]
Sejal Phatangare
Cummins College of Engineering, Pune
Sy Comp
Please assign me this issue

**Comment by shruti-2412** [comment]
Shruti Chandak
Cummins College of Engineering for Women, Pune
SY-COMP
I would like to work on this issue 
please assign it to me
