### ISSUE TITLE
Create a text summarizer using NLP

### ISSUE THREAD

**Issue by SparshRastogi** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#217]
Create an extractive text summarizer using classical NLP with the use of TF-IDF

**Comment by SparshRastogi** [comment]
@RuchikaSuryawanshi7 @JMukta25 I would like to contribute the above algorithm to the AI-ML repository as part of Hacktoberfest 2022,can you assign this to me under the Hacktoberfest label?

**Comment by RuchikaSuryawanshi7** [comment]
@SparshRastogi please create this PR in AL/ML Repository

**Comment by SparshRastogi** [comment]
Ok thanks
