### ISSUE TITLE
Add Kadane's Algorithm to the array directory 

### ISSUE THREAD

**Issue by SparshRastogi** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#222]
@RuchikaSuryawanshi7 I would like to add the implementation of the Kadane's algorithm in Python to the Array directory of your repository,could you please assign that to me so I can move forward with it

**Comment by RuchikaSuryawanshi7** [comment]
@SparshRastogi  you can work on this now

**Comment by shreya2663** [comment]
can i do it

**Comment by SparshRastogi** [comment]
> @SparshRastogi you can work on this now, make sure you explain the algorithm separately

@RuchikaSuryawanshi7 thanks,I will try to complete that by today's evening

**Comment by SparshRastogi** [comment]
@RuchikaSuryawanshi7 can I do the explanation part in the docstrings or do you need a Readme.md file for that?
